#!/bin/bash
# 此脚本是在仅能显示 ascii 字符如 tty 下时使用的。
# The script is meant to be used when only ascii characters are able to display, such as under tty.
cd "$(dirname "${BASH_SOURCE[0]}")"
mkdir -p .tempconf
touch .tempconf/ascii
./install
