#!/bin/bash
# vim:fileencoding=utf-8:ft=config:fdm=marker foldlevel=0

# 定义基本函数 - Define basic functions {{{
nofail(){
while true;do if $@
then break;fi;done
}

y(){
nofail yay -S --needed --noconfirm $1
}

p(){
nofail sudo pacman -S --needed --noconfirm $1
}
# }}}

# 确保有 AUR 助手 - Ensure AUR helper available {{{
ensureyay(){
  if test -f "/usr/bin/yay";
  then echo "/usr/bin/yay found."
  else echo "/usr/bin/yay not found, now install yay:"
    t=~/.cache/yay/; mkdir -p $t; cd $t
    p git base-devel curl
    nofail git clone https://aur.archlinux.org/yay-bin.git
    cd yay-bin
    nofail makepkg -si --noconfirm
  fi
}
# }}}

# 定义基本安装流程 - Define basic installation process {{{
#TODO List:
#Nvidia
#Intel
#Qemu/KVM/libvirt
#VirtualBox
#VMWARE
deps_basic(){
p \
git base-devel curl \
zsh neovim vifm exa bat fzf fd \
mesa xorg-xwayland sway swayidle swaybg \
mako network-manager-applet polkit-gnome \
gammastep blueman swayidle slurp grim swappy \
zenity alacritty playerctl wofi \
ttf-firacode-nerd qt5ct qt6ct ttf-nerd-fonts-symbols-mono
# If waybar-hyprland exists, then there's no need to install waybar (perhaps).
if test -f /usr/bin/waybar;then sleep 0;else p waybar;fi
y swaylock-effects clightd ttf-twemoji-color
sudo systemctl enable clightd.service --now

if [ $(cat .tempconf/genv-locale.conf) == "zh_CN" ] ; then
p \
fcitx5 fcitx5-configtool fcitx5-gtk fcitx5-qt fcitx5-nord fcitx5-rime \
wqy-microhei noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra ttf-sarasa-gothic \
adobe-source-han-sans-cn-fonts adobe-source-han-sans-hk-fonts adobe-source-han-sans-jp-fonts adobe-source-han-sans-kr-fonts adobe-source-han-sans-otc-fonts adobe-source-han-sans-tw-fonts \
adobe-source-han-serif-cn-fonts adobe-source-han-serif-jp-fonts adobe-source-han-serif-kr-fonts adobe-source-han-serif-otc-fonts adobe-source-han-serif-tw-fonts
fi
}
# }}}

# 定义显卡安装流程 - Define VGA installation process {{{
deps_vga_amd(){
  p mesa
}
# }}}
